### ISSUE TITLE
Comet Cache v161214-RC (Release Candidate)

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#858]
# General Availability Target: December 16th, 2016

## Downloads

- [Comet Cache Lite v161214-RC](https://cometcache.com/r/download-lite-v161214-rc/)
- [Comet Cache Pro v161214-RC](https://cometcache.com/r/download-pro-v161214-rc/) (requires being logged into cometcache.com)

## Changelog

- **Bug Fix:** Improving OPcache detection. Now considering INI option `opcache.restrict_api`. Comet Cache is now smart enough to avoid the error: _PHP Warning: Zend OPcache API is restricted by "restrict_api" configuration directive_. See [Issue #733](https://github.com/websharks/comet-cache/issues/733).

- **New Feature (Pro): Mobile Mode.** This release adds a new feature that is designed to improve compatibility with Adaptive themes for mobile devices. To learn more, please see: **Dashboard → Comet Cache Pro → Plugin Options → Mobile-Adaptive Mode**. See also: [Issue #471](https://github.com/websharks/comet-cache/issues/471) and the screenshots [here](https://github.com/websharks/comet-cache-pro/pull/303#issuecomment-266230409).

- **Enhancement: Auto-Clearing Author Page Cache.** This release makes Comet Cache smart enough to detect when a user is deleted (or removed from a child blog in a Network), at which time the Author page for that user will be cleared from the cache so it can be regenerated automatically. See [Issue #304](https://github.com/websharks/comet-cache/issues/304).

- **Enhancement: Multibyte Compatibility.** This release improves support for WordPress Permalinks that contain UTF-8 symbols (or emojis) in them. More specifically, this release adds the `/u` flag to all `preg_*()` calls in cache clearing routines that generate cache paths from Watered-Down Regex patterns entered by a site owner. See: [Issue #611](https://github.com/websharks/comet-cache/issues/611).

- **Enhancement: Widget Change Detection.** Comet Cache can now detect when **Appearance → Widgets** are added/edited/removed, and Comet Cache will automatically clear the cache so that your site remains up-to-date. See [Issue #411](https://github.com/websharks/comet-cache/issues/411).

- **Enhancement (Pro): Static CDN Filters and `srcset`.** This release enhances Static CDN Filters in Comet Cache Pro. Static CDN Filters are now smart enough to filter all image sources included in an `srcset=""` attribute that is generated by WordPress. See [Issue #660](https://github.com/websharks/comet-cache/issues/660). If you'd like to learn more about `srcset=""`, see [this article at WordPress.org](https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/).

- **Enhancement (Pro): Automatic Background Updates.** It is now possible to enable automatic background updates that occur quietly in the background whenever new features, bug fixes, or security issues are addressed by our developers. See: **Dashboard → Comet Cache Pro → Config. Options → Update Credentials**. See also: [Issue #827](https://github.com/websharks/comet-cache/issues/827).

- **Enhancement (Pro): HTML Compressor + Accelerated Mobile Pages (AMP).** Updated to the latest available release of the HTML Compressor (v161208) with improved support for [Accelerated Mobile Pages](https://www.ampproject.org/). See: [Issue #733](https://github.com/websharks/comet-cache/issues/733). See also: [HTML Compressor v161208 changelog](https://github.com/websharks/html-compressor/releases/tag/161208).

- **Enhancement (Pro): HTML Compressor / AMP Compatibility.** Improved compatibility with [Accelerated Mobile Pages](https://www.ampproject.org/). There is a new HTML Compressor option that is enabled by default and it makes Comet Cache smart enough to auto-detect and selectively disable portions of the HTML Compressor that are incompatible with the AMP spec; i.e., routines that are not necessary when serving APMd pages. In short, if the URI being compressed ends with `/amp/`, or the document contains a top-level `<html ⚡>` tag (`<html amp>` is accepted as well), then features which are incompatible with [Accelerated Mobile Pages](https://www.ampproject.org/) will be disabled accordingly.

- **Compatibility:** Avoid deprecated `wp_get_sites()` and use `get_sites()` instead. See [Issue #848](https://github.com/websharks/comet-cache/issues/848).

- **Documentation:** Added Watered-Down Regex documentation notes to the inline documentation (in the software) about the use of `^` and `$` in some places where these special characters are not fully supported. Also adding the same notes to the [Watered-Down Regex KB Article](https://cometcache.com/r/watered-down-regex-syntax/). See also: [Issue #611](https://github.com/websharks/comet-cache/issues/611).

See also: [Comet Cache v161214-RC Release Announcement](https://cometcache.com/blog/comet-cache-v161214-rc-release-candidate/)

## Reporting Issues / Feedback

Please report any issues or feedback related to this Release Candidate using this GitHub issue. Please post a comment below with details. 

If you are reporting a UI-related issue, please include a screenshot.

If you are reporting a bug, please provide list of steps to reproduce and if the bug is related to an existing GitHub issue, please provide a link to that GitHub issue as well.

---- 

## Reported Issues to Fix

_None at this time._

**Comment by raamdev** [comment]
## @jaswsinc `TODO`

- [x] Ensure the Mobile Mode `browser.version` token is updated to only contain the `[major].[minor]` version numbers.

----

[Jason wrote in Slack](https://websharks.slack.com/archives/comet-cache/p1481662924000033):
> Regarding mobile mode. Just an idea, but the current `browser.version` token is the full complete version (e.g., 1.2.12923923-alpha) and that's not very useful. In the future, or sometime between now and the official release, we should probably change `browser.version` so that it only contains the `[major].[minor]` version numbers. That way when this is used by others who need it, it's not just absolutely nuts to turn this on. Right now, it's fairly unreasonable to assume anyone could use that and actually make it work with any stability.

**Comment by renzms** [comment]
### Confirmed Working

- [x] **Documentation:** Added Watered-Down Regex documentation notes to the inline documentation (in the software) about the use of `^` and `$` in some places where these special characters are not fully supported. Also adding the same notes to the [Watered-Down Regex KB Article](https://cometcache.com/r/watered-down-regex-syntax/). See also: [Issue #611](https://github.com/websharks/comet-cache/issues/611).

- [x] **Enhancement: Widget Change Detection.** Comet Cache can now detect when **Appearance → Widgets** are added/edited/removed, and Comet Cache will automatically clear the cache so that your site remains up-to-date. See [Issue #411](https://github.com/websharks/comet-cache/issues/411).

- [x] **Enhancement (Pro): Automatic Background Updates.** It is now possible to enable automatic background updates that occur quietly in the background whenever new features, bug fixes, or security issues are addressed by our developers. See: **Dashboard → Comet Cache Pro → Config. Options → Update Credentials**. See also: [Issue #827](https://github.com/websharks/comet-cache/issues/827).

- [x] **Enhancement: Auto-Clearing Author Page Cache.** This release makes Comet Cache smart enough to detect when a user is deleted (or removed from a child blog in a Network), at which time the Author page for that user will be cleared from the cache so it can be regenerated automatically. See [Issue #304](https://github.com/websharks/comet-cache/issues/304).


- [x] **Enhancement: Multibyte Compatibility.** This release improves support for WordPress Permalinks that contain UTF-8 symbols (or emojis) in them. More specifically, this release adds the `/u` flag to all `preg_*()` calls in cache clearing routines that generate cache paths from Watered-Down Regex patterns entered by a site owner. See: [Issue #611](https://github.com/websharks/comet-cache/issues/611).


- [x] **Enhancement (Pro): Static CDN Filters and `srcset`.** This release enhances Static CDN Filters in Comet Cache Pro. Static CDN Filters are now smart enough to filter all image sources included in an `srcset=""` attribute that is generated by WordPress. See [Issue #660](https://github.com/websharks/comet-cache/issues/660). If you'd like to learn more about `srcset=""`, see [this article at WordPress.org](https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/).


- [x] **Compatibility:** Avoid deprecated `wp_get_sites()` and use `get_sites()` instead. See [Issue #848](https://github.com/websharks/comet-cache/issues/848).


- [x] **Enhancement (Pro): HTML Compressor + Accelerated Mobile Pages (AMP).** Updated to the latest available release of the HTML Compressor (v161208) with improved support for [Accelerated Mobile Pages](https://www.ampproject.org/). See: [Issue #695 ](https://github.com/websharks/comet-cache/issues/695). See also: [HTML Compressor v161208 changelog](https://github.com/websharks/html-compressor/releases/tag/161208).

- [x] **Enhancement (Pro): HTML Compressor / AMP Compatibility.** Improved compatibility with [Accelerated Mobile Pages](https://www.ampproject.org/). There is a new HTML Compressor option that is enabled by default and it makes Comet Cache smart enough to auto-detect and selectively disable portions of the HTML Compressor that are incompatible with the AMP spec; i.e., routines that are not necessary when serving APMd pages. In short, if the URI being compressed ends with `/amp/`, or the document contains a top-level `<html ⚡>` tag (`<html amp>` is accepted as well), then features which are incompatible with [Accelerated Mobile Pages](https://www.ampproject.org/) will be disabled accordingly.

- [x] **Bug Fix:** Improving OPcache detection. Now considering INI option `opcache.restrict_api`. Comet Cache is now smart enough to avoid the error: _PHP Warning: Zend OPcache API is restricted by "restrict_api" configuration directive_. See [Issue #733](https://github.com/websharks/comet-cache/issues/733).


- [x] **New Feature (Pro): Mobile Mode.** This release adds a new feature that is designed to improve compatibility with Adaptive themes for mobile devices. To learn more, please see: **Dashboard → Comet Cache Pro → Plugin Options → Mobile-Adaptive Mode**. See also: [Issue #471](https://github.com/websharks/comet-cache/issues/471) and the screenshots [here](https://github.com/websharks/comet-cache-pro/pull/303#issuecomment-266230409).

**Comment by renzms** [comment]
@raamdev 

For the panels that use Watered Down REGEX and have external links, they correctly redirect and have the redirect links at `http://cometcache.com/r/`.

http://cometcache.com/r/watered-down-regex-syntax/ - https://cometcache.com/kb-article/watered-down-regex-syntax/

For the following, should we put them on a domain we own and redirect?

`REQUEST_URI` - https://gist.github.com/jaswsinc/338b6eb03a36c048c26f

`HTTP_REFERER` - http://php.net//manual/en/reserved.variables.server.php
 
`HTTP_USER_AGENT` - http://php.net//manual/en/reserved.variables.server.php

**Comment by KTS915** [comment]
Using Firefox mobile on Android on my localhost test site running Linux Mint 17.3, I get the following message:
```
Array to string conversion in /var/www/html/blog/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/Conditional/Utils.php on line 156
```

**Comment by raamdev** [comment]
@KTS915 Thanks for the report!

@jaswsinc Here's line 156 reported above:
https://github.com/websharks/comet-cache-pro/blob/161214-RC/src/includes/traits/Shared/ConditionalUtils.php#L156

Anything you're seeing there that might warrant holding up the release?

**Comment by KTS915** [comment]
@raamdev @jaswsinc I am now getting this error message on Chrome as well. (Strangely, I wasn't getting it before.)

**Comment by jaswrks** [comment]
Taking a look at this now.

**Comment by jaswrks** [comment]
@KTS915  Thanks for reporting this.

Based on [the iteration that error points to](https://github.com/websharks/comet-cache-pro/blob/161214-RC/src/includes/traits/Shared/ConditionalUtils.php#L156), I'd say the most likely cause of this is a rogue plugin. It's not possible to store an array in a cookie. Only a string or numeric value. So if the `$_COOKIE` superglobal contains a key holding an array, the only way I can see this happening is if another theme or plugin is forcing it to contain an array, at runtime.

@raamdev Having said that, we can add an `is_string()` check to this iteration instead of _only_ typecasting it, just to avoid this error from occurring. I don't see this needing to hold up a release, but it's also a quick fix if you'd like to tweak it. In that iteration, if the value is not a string, we should just `continue` past it instead of trying to convert it.

**Comment by KTS915** [comment]
@jaswsinc: Sadly, it doesn't appear to be a rogue plugin or custom theme. I've just tried both browsers on my Android phone on the same site, but with the 2015 theme and all plugins except CC deactivated. I also cleared the browser caches. I still get the same messages.

What seems strange to me is that this is not happening on my desktop PC with either browser.

**Comment by raamdev** [comment]
@KTS915 Have you tried clearing the browser cache on those mobile browsers, just in case the cookie(s) got corrupted somehow?

**Comment by KTS915** [comment]
@raamdev : Yes, I did.

**Comment by raamdev** [comment]
**Comet Cache v161221** has been released and includes changes from this GitHub Issue. See the [v161221 announcement](https://cometcache.com/blog/comet-cache-v161221-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#858).
