### ISSUE TITLE
Comet Cache Pro v161223-RC (Maintenance Release Candidate)

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#863]
# General Availability Target: December 26th, 2016

_**Note:** This is a release candidate for a Pro maintenance release._

## Downloads

- [Comet Cache Pro v161223-RC](https://cometcache.com/r/download-pro-v161223-rc/) (requires being logged into cometcache.com)

## Changelog

- **Bug Fix** (Pro): Resolves error `Unable to determine UA info directory location` when upgrading to latest release. See [Issue #862](https://github.com/websharks/comet-cache/issues/862).
- **Bug Fix** (Pro): Enhancing compatibility with InfiniteWP, ManageWP, and other remote management tools for WordPress. See [Issue #862](https://github.com/websharks/comet-cache/issues/862).
- **Bug Fix** (Pro): Incorrect time calculations whenever load average checks are enabled in Comet Cache configuration options. See [Issue #853](https://github.com/websharks/comet-cache/issues/853).
- **Cleanup:** Removed an old API call that checked for a newer lite version. No longer necessary.

See also: [Comet Cache Pro v161223-RC Release Announcement](https://cometcache.com/blog/comet-cache-pro-v161223-rc-maintenance-release-candidate/)

## Reporting Issues / Feedback

Please report any issues or feedback related to this Release Candidate using this GitHub issue. Please post a comment below with details. 

If you are reporting a UI-related issue, please include a screenshot.

If you are reporting a bug, please provide list of steps to reproduce and if the bug is related to an existing GitHub issue, please provide a link to that GitHub issue as well.

---- 

## Reported Issues to Fix

_None at this time._

**Comment by renzms** [comment]
@raamdev 


### All Fixes Confirmed Working 👍 

- [x] Bug Fix (Pro): Resolves error `Unable to determine UA info directory location` when upgrading to latest release. See Issue #862.
- [x] Bug Fix (Pro): Enhancing compatibility with InfiniteWP, ManageWP, and other remote management tools for WordPress. See Issue #862.
- [x] Bug Fix (Pro): Incorrect time calculations whenever load average checks are enabled in Comet Cache configuration options. See Issue #853.


**Tested Using**

WordPress Version: 4.7
Current WordPress Theme: Twenty Sixteen version 1.3
Theme Author: the WordPress team - https://wordpress.org/
Theme URI: https://wordpress.org/themes/twentysixteen/
Active Plugins: Comet Cache Pro v161223-RC 
PHP Version: 7.0.10-2+deb.sury.org~xenial+1
MySQL Version: 10.0.28-MariaDB-0ubuntu0.16.04.1

Tested using Single Site install and Network Installations


###  Bug Fix (Pro): Resolves error `Unable to determine UA info directory location` when upgrading to latest release. + Enhancing compatibility with remote management tools for WordPress

**Infinite WP seems to have errors with its WP Dashboard Installation** 
>
>![screen shot 2016-12-24 at 12 14 54 pm](https://cloud.githubusercontent.com/assets/13220018/21465179/7607e56c-c9d3-11e6-88d3-b1f3cf18f363.png)

**Used ManageWP instead to test for Remote Management upgrade**

ManageWP Dashboard detects Comet Cache PRO RC available for upgrade
>
>![screen shot 2016-12-24 at 12 12 47 pm](https://cloud.githubusercontent.com/assets/13220018/21465181/760d7b9e-c9d3-11e6-810b-ea8055557f08.png)


ManageWP Dashboard after upgrading to Comet Cache Pro v161223-RC
>![screen shot 2016-12-24 at 12 14 02 pm](https://cloud.githubusercontent.com/assets/13220018/21465178/7606a0da-c9d3-11e6-9566-6ea4583d818d.png)


WP Dashboard Plugins list. Upon visiting, it detects Comet Cache Pro v161223-RC and clears cache
>![screen shot 2016-12-24 at 12 13 49 pm](https://cloud.githubusercontent.com/assets/13220018/21465180/7608dc24-c9d3-11e6-9a97-a729ca44e838.png)




______________

### Bug Fix (Pro): Incorrect time calculations


**Cache Expiration Time settings**

- set at `28` days
- Server Load average set to `.01`
>![screen shot 2016-12-24 at 12 16 14 pm](https://cloud.githubusercontent.com/assets/13220018/21465176/75fe2716-c9d3-11e6-9720-747f20855ca0.png)

- Time is calculated Correctly


>![screen shot 2016-12-24 at 12 26 22 pm](https://cloud.githubusercontent.com/assets/13220018/21465210/3aafdd98-c9d4-11e6-95f5-44866f314359.png)


>![screen shot 2016-12-24 at 12 18 45 pm](https://cloud.githubusercontent.com/assets/13220018/21465177/75fe37ba-c9d3-11e6-97bc-9ac66d4269a6.png)

**Comment by raamdev** [comment]
**Comet Cache Pro v161226** has been released and includes changes from this GitHub Issue. See the [v161226 announcement](https://cometcache.com/blog/comet-cache-pro-v161226-maintenance-release/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#863).
