### ISSUE TITLE
Comet Cache v170201-RC (Release Candidate)

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#874]
### Downloads

- [Comet Cache Lite v170201-RC](http://cometcache.com/r/download-lite-v170201-rc/)
- [Comet Cache Pro v170201-RC](https://cometcache.com/r/download-pro-v170201-rc/) (requires being logged into cometcache.com)

### Changelog

- **New Feature:** Comet Cache can now be configured to automatically clear the cache for date-based archive views whenever any single post is cleared due to changes in content, title, etc. See: **Dashboard → Comet Cache → Plugin Options → Automatic Cache Clearing → Auto-Clear "Date-Based Archives" Too?**. See also: [Issue #724](https://github.com/websharks/comet-cache/issues/724).
- **New Pro Feature:** Apache Optimizations now include a new option that allows site owners to enforce an exact host name for all requests. See: **Dashboard → Comet Cache Pro → Plugin Options → Apache Optimizations → Enforce an Exact Host Name?**. See also: [Issue #101](https://github.com/websharks/comet-cache/issues/101).
- **Bug Fix:** Apache detection sometimes inaccurate. So instead of using default WP core globals for server detection, Comet Cache now uses it's own set of Apache/Nginx/IIS detection functions. And, this release enhances our Apache and Nginx detection routines; making them smart enough to catch additional edge cases; i.e., to further reduce the likelihood of there being a false-positive. See [Issue #748](https://github.com/websharks/comet-cache/issues/748).
- **Bug Fix:** Some XML-RPC and REST API requests were being cached inadvertently. See [Issue #855](https://github.com/websharks/comet-cache/issues/855).
- **Bug Fix:** Broken textarea field due to `white-space:nowrap` in Firefox. See [Issue #866](https://github.com/websharks/comet-cache/issues/866).
- **Bug Fix:** This release resolves empty directories being left in the cache folder, in some scenarios. See [Thread #866](https://forums.wpsharks.com/t/cache-folders-not-removed-during-clean-up-process/866).
- **Bug Fix** (Pro): Some REST requests were being redirected incorrectly whenever Apache Optimizations were enabled. See [Issue #855](https://github.com/websharks/comet-cache/issues/855).
- **Compatibility Bug Fix:** Some Jetpack API calls were being cached inadvertently. See [Issue #855](https://github.com/websharks/comet-cache/issues/855).
- **Enhancement:** Notes in HTML source now indicate fully functional on first load for improved clarity. See [Issue #860](https://github.com/websharks/comet-cache/issues/860).
- **Enhancement:** Enhancing security by removing `basename(__FILE__)` from direct access notices.

See also: [Comet Cache v170201-RC Release Announcement](http://cometcache.com/blog/comet-cache-v170201-rc-release-candidate/)

### Reporting Issues / Feedback

Please report any issues or feedback related to this Release Candidate using this GitHub issue. Please post a comment below with details. 

If you are reporting a UI-related issue, please include a screenshot.

If you are reporting a bug, please provide list of steps to reproduce and if the bug is related to an existing GitHub issue, please provide a link to that GitHub issue as well.

---- 

## Reported Issues to Fix

_None at this time._

**Comment by renzms** [comment]
### Tested
- [x] **Bug Fix:** Broken textarea field due to `white-space:nowrap` in Firefox. See [Issue #866](https://github.com/websharks/comet-cache/issues/866).
- [x] **Bug Fix:** This release resolves empty directories being left in the cache folder, in some scenarios. See [Thread #866](https://forums.wpsharks.com/t/cache-folders-not-removed-during-clean-up-process/866).
- [x] **Enhancement:** Notes in HTML source now indicate fully functional on first load for improved clarity. See [Issue #860](https://github.com/websharks/comet-cache/issues/860).
- [x] **New Feature:** Comet Cache can now be configured to automatically clear the cache for date-based archive views whenever any single post is cleared due to changes in content, title, etc. See: **Dashboard → Comet Cache → Plugin Options → Automatic Cache Clearing → Auto-Clear "Date-Based Archives" Too?**. See also: [Issue #724](https://github.com/websharks/comet-cache/issues/724).

- [x] **Bug Fix:** Apache detection sometimes inaccurate. So instead of using default WP core globals for server detection, Comet Cache now uses it's own set of Apache/Nginx/IIS detection functions. And, this release enhances our Apache and Nginx detection routines; making them smart enough to catch additional edge cases; i.e., to further reduce the likelihood of there being a false-positive. See [Issue #748](https://github.com/websharks/comet-cache/issues/748).

- [x] **Compatibility Bug Fix:** Some Jetpack API calls were being cached inadvertently. See [Issue #855](https://github.com/websharks/comet-cache/issues/855).

- [x] **Bug Fix:** Some XML-RPC and REST API requests were being cached inadvertently. See [Issue #855](https://github.com/websharks/comet-cache/issues/855).

- [x] **Bug Fix** (Pro): Some REST requests were being redirected incorrectly whenever Apache Optimizations were enabled. See [Issue #855](https://github.com/websharks/comet-cache/issues/855).



- [x] **New Pro Feature:** Apache Optimizations now include a new option that allows site owners to enforce an exact host name for all requests. See: **Dashboard → Comet Cache Pro → Plugin Options → Apache Optimizations → Enforce an Exact Host Name?**. See also: [Issue #101](https://github.com/websharks/comet-cache/issues/101).

**Comment by raamdev** [comment]
@renzms I'm publishing a new RC after the recent bug fixes that Jason pushed to the RC branch for #724 and #748. Please run new tests for the items on the "Tested with Issues" list using this new RC and finish your "Ongoing Tests" with this new RC as well. It's not necessary to re-test the "Tested" items.

----

## NEW RELEASE CANDIDATE: Comet Cache v170209-RC

_This updated RC includes fixes for issues found while testing #724 and #748._
- [Comet Cache Lite v170209-RC](https://github.com/websharks/comet-cache/files/765463/comet-cache-v170209-RC.zip)
- [Comet Cache Pro v170209-RC](https://cometcache.com/?s2member_file_download=/ccaps/access-s2member-ccap-pro/comet-cache-pro-v170209-RC.zip) (requires being logged into cometcache.com)

**Comment by renzms** [comment]
@raamdev 


Fixes and enhancements confirmed working for Comet Cache Pro v170209-RC

**Comment by raamdev** [comment]
**Comet Cache v170220** has been released and includes changes from this GitHub Issue. See the [v170220 announcement](https://cometcache.com/blog/comet-cache-v170220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#874).
