### ISSUE TITLE
Comet Cache v170808-RC (Release Candidate)

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#909]
### Downloads

- [Comet Cache Lite v170808-RC](https://cometcache.com/r/download-lite-v170808-rc/)
- [Comet Cache Pro v170808-RC](https://cometcache.com/r/download-pro-v170808-rc/) (requires being logged into cometcache.com)

### Changelog

- **New Feature: Memcached / RAM** (Pro): Comet Cache Pro now includes support for Memcached / AWS ElastiCache to serve the cache directly from RAM. This allows for a faster cache delivery than what is possible when serving the cache via disk. Memcached / AWS ElastiCache can be configured from **Dashboard → Comet Cache Pro → Plugin Options → RAM / Memcached**. See [Issue #47](https://github.com/websharks/comet-cache/issues/47)
- **Enhancement**: Added `Referrer-Policy` to whitelist for cachable HTTP headers. See [Issue #892](https://github.com/websharks/comet-cache/issues/892).
- **Bug Fix** (Pro): The Cache Statistics feature was broken when the PHP `disk_total_space()` and/or `disk_free_space()` functions were disabled by the PHP configuration. Comet Cache now handles this scenario gracefully by hiding disk-related stats when those functions are not allowed. See [Issue #775](https://github.com/websharks/comet-cache/issues/775)
- **Bug Fix** (Pro): The HTML Compressor was returning an empty string upon encountering an invalid UTF-8 sequence. See [Issue #871](https://github.com/websharks/comet-cache/issues/871) reported by a Comet Cache user.
- **Compatibility** (Pro): Many improvements to the Pro software update system, including changes to the API Endpoints and the Proxy Fallback endpoint. See [Issue #879](https://github.com/websharks/comet-cache/issues/879) and [Issue #315](https://github.com/websharks/comet-cache-pro/pull/315) for full details.
- **Compatibility**: Fixed a WooCommerce compatibility issue that was generating a "Notice: id was called incorrectly. Product properties should not be accessed directly." Props @vestaxpdx. See [Issue #896](https://github.com/websharks/comet-cache/issues/896).

See also: [Comet Cache v170808-RC Release Announcement](http://cometcache.com/blog/comet-cache-v170808-rc-release-candidate/)

### Reporting Issues / Feedback

Please report any issues or feedback related to this Release Candidate using this GitHub issue. Please post a comment below with details. 

If you are reporting a UI-related issue, please include a screenshot.

If you are reporting a bug, please provide list of steps to reproduce and if the bug is related to an existing GitHub issue, please provide a link to that GitHub issue as well.

---- 

## Reported Issues to Fix

_None at this time._

**Comment by renzms** [comment]
**Tested using:**

WordPress Version: 4.8-RC2-40880
Current WordPress Theme: Twenty Seventeen version 1.3
Theme Author: the WordPress team - https://wordpress.org/
Theme URI: https://wordpress.org/themes/twentyseventeen/
Active Plugins: Comet Cache Pro v170808-RC , Google XML Sitemaps Version 4.0.9 
PHP Version: 7.1.3-3+deb.sury.org~xenial+1
MySQL Version: 10.0.31-MariaDB-0ubuntu0.16.04.2



### Confirmed Working

- [x]  **Bug Fix** (Pro): The HTML Compressor was returning an empty string upon encountering an invalid UTF-8 sequence. See [Issue #871](https://github.com/websharks/comet-cache/issues/871) reported by a Comet Cache user.

<details><summary> Click for Results  </summary>

>
>- When invalid UTF-8 is encountered by Comet Cache's HTML Compressor, the display notes will now reflect why the compressor was not run in that instance.

>
>![test utf8](https://user-images.githubusercontent.com/13220018/29164838-733bcf68-7df3-11e7-8c37-cb8abb3a3506.png)

</details>

- [x]  **Compatibility**: Fixed a WooCommerce compatibility issue that was generating a "Notice: id was called incorrectly. Product properties should not be accessed directly." Props @vestaxpdx. See [Issue #896](https://github.com/websharks/comet-cache/issues/896).


<details><summary> Click for Results  </summary>

>
>- No issues found after checkout, checkout is successful.

>
>![Checkout Success](https://user-images.githubusercontent.com/13220018/29167856-bf692b64-7dfe-11e7-8207-49a0ac0249ab.png)


</details>


- [x]  **New Feature: Memcached / RAM** (Pro): Comet Cache Pro now includes support for Memcached / AWS ElastiCache to serve the cache directly from RAM. This allows for a faster cache delivery than what is possible when serving the cache via disk. Memcached / AWS ElastiCache can be configured from **Dashboard → Comet Cache Pro → Plugin Options → RAM / Memcached**. See [Issue #47](https://github.com/websharks/comet-cache/issues/47)

### Currently Testing

- [ ]  **Enhancement**: Added `Referrer-Policy` to whitelist for cachable HTTP headers. See [Issue #892](https://github.com/websharks/comet-cache/issues/892).
- [ ]  **Bug Fix** (Pro): The Cache Statistics feature was broken when the PHP `disk_total_space()` and/or `disk_free_space()` functions were disabled by the PHP configuration. Comet Cache now handles this scenario gracefully by hiding disk-related stats when those functions are not allowed. See [Issue #775](https://github.com/websharks/comet-cache/issues/775)

- [ ]  **Compatibility** (Pro): Many improvements to the Pro software update system, including changes to the API Endpoints and the Proxy Fallback endpoint. See [Issue #879](https://github.com/websharks/comet-cache/issues/879) and [Issue #315](https://github.com/websharks/comet-cache-pro/pull/315) for full details.

**Comment by raamdev** [comment]
## Bug in Pro Updater for RC updates

@jaswrks and I discovered a bug in the Pro Updater that prevented the installation of Beta Updates via the built-in Pro Updater. This bug doesn't cause any harm, but it did prevent RC versions from being installed via the Pro Updater, which meant that any Pro users who were opting into Beta Updates via the built-in Pro Updater were not actually receiving them. @jaswrks is working on a fix now and we'll have the fix rolled into the upcoming General Availability release.

Note that this isn't a _new_ bug; this bug has existed for awhile and we only now discovered it while testing v170808-RC.

**Comment by raamdev** [comment]
I rebuilt the Lite and Pro the version from the latest version of the `release/170808-RC` branch and discovered the following issues:

## Lite Version

Upon installation:

```
  |  
-- | --
  | Fatal error: Uncaught Exception: Undefined method/closure: `versionCompare`. in /app/src/wp-content/plugins/comet-cache/src/includes/classes/AbsBaseAp.php on line 73
  |  
  | Exception: Undefined method/closure: `versionCompare`. in /app/src/wp-content/plugins/comet-cache/src/includes/classes/AbsBaseAp.php on line 73
  |  
  | Call Stack:
  | 0.0004     384648   1. {main}() /app/src/wp-admin/plugins.php:0
  | 0.0005     385320   2. require_once('/app/src/wp-admin/admin.php') /app/src/wp-admin/plugins.php:10
  | 0.0006     385800   3. require_once('/app/src/wp-load.php') /app/src/wp-admin/admin.php:31
  | 0.0010     400552   4. require_once('/app/src/wp-config.php') /app/src/wp-load.php:37
  | 0.0012     408848   5. require_once('/app/src/wp-settings.php') /app/src/wp-config.php:43
  | 0.0897    3544592   6. do_action() /app/src/wp-settings.php:448
  | 0.0897    3544968   7. WP_Hook->do_action() /app/src/wp-includes/plugin.php:453
  | 0.0897    3544968   8. WP_Hook->apply_filters() /app/src/wp-includes/class-wp-hook.php:323
  | 0.1327    3906448   9. WebSharks\CometCache\Classes\Plugin->checkVersion() /app/src/wp-includes/class-wp-hook.php:298
  | 0.1327    3906448  10. WebSharks\CometCache\Classes\AbsBaseAp->versionCompare() /app/src/wp-content/plugins/comet-cache/src/includes/traits/Plugin/InstallUtils.php:54
  | 0.1327    3906824  11. WebSharks\CometCache\Classes\AbsBaseAp->__call() /app/src/wp-content/plugins/comet-cache/src/includes/traits/Plugin/InstallUtils.php:54
  |  
```

# Pro Version

Upon installation:

```
PHP Warning:  Illegal string offset 'rv' in /home/raamdev/public_html/wordpress/wp-content/plugins/comet-cache-pro/plugin.php on line 5
PHP Warning:  Illegal string offset 're' in /home/raamdev/public_html/wordpress/wp-content/plugins/comet-cache-pro/plugin.php on line 6
PHP Notice:  Array to string conversion in /home/raamdev/public_html/wordpress/wp-content/plugins/comet-cache-pro/plugin.php on line 6
```

**Comment by jaswrks** [comment]
@raamdev 

- The issue in lite regarding `versionCompare()` has been corrected.
- The issue with illegal string offset `rv`, `re` in `plugin.php` I was unable to reproduce. However, I did take a look at the `plugin.php` file and it seems to me the only way that could happen is if the WP PHP RV plugin was missing; e.g., `composer install` was not run, or failed to acquire WP PHP RV in your last attempt. So I think that was a transient error. So not a bug.

**Comment by renzms** [comment]
@raamdev 

![413 error](https://user-images.githubusercontent.com/13220018/30262369-3a82dbfc-9703-11e7-9394-b108cf71c7e1.png)


When uploading Comet Cache Pro 170808-RC (build 3) on NGINX server (PHP versions 5.4-7.1), the following error appears:

`413 Request Entity Too Large`

PHP Version: 5.4.45, 5.5.38, 5.6.30, 7.0.17
MySQL Version: 10.0.31-MariaDB-0ubuntu0.16.04.2
Apache Version: Apache/2.4.10 (Debian)

_____

Uploading and installing Comet Cache™ Pro v170220 has no problem on same sites.

For Non-NGINX server, plugin installed and work successfully for Comet Cache Pro 170808-RC (build 3).

**Comment by raamdev** [comment]
Installed and tested Comet Cache Pro 170808-RC (build 3) on **Apache/2.4.18**. No issues. 👍 
Installed and tested Comet Cache Lite 170808-RC (build 3) on **Nginx/1.11.9**. No issues. 👍

**Comment by ivarbergman** [comment]
Hi Comet Cache!

I trying to enable Memcached for a Heroku hosted site. We use MemCachier that requires SASL authentication and binary protocol. 

Is SASL authentication supported by the current RC of Comect Cache Memcached?

Cheers!

**Comment by octavianparalescu** [comment]
Hello, pro user here. Thanks for the work to bring Memcached to Comet Cache.

Tested the latest release with Memcached on a AWS ELB configuration with 2 servers. We did that so we have a centralised cache repository. I found this issues so far:
1. Cache files are still created in the filesystem even if a memcached item is set for that url. I guess we should be able to disable that feature.
2. When the "auto-clearing" of cache fires for a file, all the cache files will be deleted as you can see at this call: wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/CacheDirUtils.php:272 and all the calls to that method are only with the main cache key: 
![image](https://user-images.githubusercontent.com/5434967/32908446-44cd041a-cb0c-11e7-8d9e-3c148bcba886.png)
3. Cache stats are about the dir. Taking into consideration point 1, they should be about the memcached storage.

**Comment by jamescl** [comment]
Hi,

Looks like the htaccess template files are pointing to the wrong directory - on the plugin settings page, querymonitor shows errors for each of the template files. The files exist, but in a different directory (not in **classes/MenuPage/**)

`file_get_contents(../wp-content/plugins/comet-cache-pro/src/includes/classes/MenuPage/templates/htaccess/access-control-allow-origin-enable.txt): failed to open stream: No such file or directory`

**Comment by raamdev** [comment]
@ivarbergman writes...
> Is SASL authentication supported by the current RC of Comect Cache Memcached?

No, sorry, SASL authentication is not supported at this time. 

----

@OctavianParalescu writes...
> Cache files are still created in the filesystem even if a memcached item is set for that url. I guess we should be able to disable that feature.

Thank you. I will look into this.

@OctavianParalescu writes...
> When the "auto-clearing" of cache fires for a file, all the cache files will be deleted

Yes, unfortunately this is necessary due to limitations in the simple approach taken by Memcached (in terms of how we can clear the cache). 

@OctavianParalescu writes...
> Cache stats are about the dir. Taking into consideration point 1, they should be about the memcached storage.

Agreed. I will take this into consideration in a future release.

----

@jamescl writes...
> Looks like the htaccess template files are pointing to the wrong directory

Thank you very much for the heads up! I'll get this corrected before release.

----

For everyone looking for an update on the next release: Thank you very much for your continued patience. We fell behind quite a bit on our release schedule, but a new release will be coming very soon.

**Comment by Solgaz** [comment]
Hello!
Thanks for such a nice plugin!
I have a small problem!
Wordpress  4.9.5
WooCommerce 3.3.5
Comet Cache v170808-RC (Release Candidate)
When RAM Memcached is turned on, sometimes error 503 appears
my site: http://www.solgaz.space/

**Comment by gbruzzo** [comment]
Hello There 
Are there any news about the next release? Please advise, it has been more than a year now. 
Thank you in advance 
Giacomo Bruzzo

**Comment by vestaxpdx** [comment]
This is by far the best caching plugin out there, I really hope it's still being maintained.

**Comment by Solgaz** [comment]
Отлично все работает!!!

**Comment by jpSimkins** [comment]
Is this still not in the PRO version? 

I just installed the latest from my account `comet-cache-pro-v170220.zip` and there is no option for memcached. I was trying to ditch W3TC but without memcached support this is impossible to use.
